config/routes.rb
Rails.application.routes.draw do

  # Authorization
  devise_for :users

  # Oauth return
  get '/auth/:provider/callback', to: 'manage/providers#authorize'
  get '/auth/:provider/setup', to: 'manage/providers#setup'

  # Admin routes
  namespace :manage do
    resource :site
    resources :pages do
      collection do
        post 'reorder'
      end
    end
    resources :providers do
      collection do
        get 'authorize'
      end
    end
  end

  # Shortcuts
  get '/manage', to: 'manage/sites#show'

  # Home
  get '/:slug', to: 'site#show'
  root 'site#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github.rb
class Github < Provider

  def sync
    if self.token
      uri = URI("https://api.github.com/users/#{self.username}/events")
      req = Net::HTTP::Get.new(uri)
      req["Authorization"] = "Bearer #{self.token}"
      response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == 'https') { |http| http.request(req) }
      feed = JSON.parse(response.body)
      feed.each do |upd|
        if Update.where(originalid: upd['id'], provider_id: self.id).count == 0
          status = self.updates.build({ originalid: upd['id'], link: "https://github.com/#{upd['repo']['name']}", posted_on: upd['created_at'] })
          case upd['type']
            when "PullRequestReviewCommentEvent", "CommitCommentEvent"
              status.heading = "commented"
              status.content = upd["payload"]["comment"]["body"]
						  status.link = upd["payload"]["comment"]["html_url"]
					  when "CreateEvent"
						  ref_type = upd["payload"]["ref_type"]
						  ref = upd["repo"]["name"]
              ref = upd["payload"]["ref"] if ref_type != "repository"
						  status.heading = "created " + ref_type + " " + ref
					  when "DeleteEvent"
						  status.heading = "deleted " + upd["payload"]["ref_type"]
					  when "DownloadEvent"
						  status.heading = "uploaded " + upd["payload"]["download"]["name"]
						  status.link = upd["payload"]["download"]["html_url"]
					  when "FollowEvent"
						  status.heading = "is now following " + upd["payload"]["target"]["login"]
						  status.link = upd["payload"]["target"]["html_url"]
					  when "ForkEvent"
						  status.heading = "forked " + upd["repo"]["name"]
					  when "ForkApplyEvent"
						  status.heading = "applied fork to " + upd["payload"]["head"]
					  when "GistEvent"
						  status.heading = upd["payload"]["action"] + "d " + upd["payload"]["gist"]["description"]
						  status.link = upd["payload"]["gist"]["html_url"]
					  when "GollumEvent"
						  status.heading = upd["payload"]["pages"][0]["action"] + " page"
						  status.content = upd["payload"]["pages"][0]["page_name"]
						  status.link = upd["payload"]["pages"][0]["html_url"]
					  when "IssueCommentEvent"
						  status.heading = upd["payload"]["action"] + " on issue \#" +  upd["payload"]["issue"]["number"].to_s
						  status.content = upd["payload"]["comment"]["body"]
						  status.link = upd["payload"]["issue"]["html_url"]
					  when "IssuesEvent"
						  status.heading = upd["payload"]["action"] + " issue \#" +  upd["payload"]["issue"]["number"].to_s
						  status.content = upd["payload"]["issue"]["body"]
						  status.link = upd["payload"]["issue"]["html_url"]
					  when "MemberEvent"
						  status.heading = upd["payload"]["action"] + " " +  upd["payload"]["member"]["login"] + " to " + upd["repo"]["name"]
						  status.link = upd["payload"]["member"]["html_url"]
					  when "PublicEvent"
						  status.heading = "Open sourced " + upd["repo"]["name"]
					  when "PullRequestEvent"
						  status.heading = upd["payload"]["action"] + " pull request"
						  status.content = upd["payload"]["pull_request"]["title"]
						  status.link = upd["payload"]["pull_request"]["html_url"]
					  when "PushEvent"
						  status.heading = "pushed to " + upd["repo"]["name"]
						  status.content = upd["payload"]["commits"][0]["message"] unless upd["payload"]["commits"].blank?
					  when "TeamAddEvent"
						  status.heading = "added " + upd["payload"]["user"]["login"] + " to " + upd["payload"]["team"]["name"]
						  status.link = upd["payload"]["user"]["html_url"]
					  when "WatchEvent"
						  status.heading = upd["payload"]["action"] + " watching " + upd["repo"]["name"]
          end
          status.save
        end
      end
    end
  end

end

app/models/page.rb
class Page < ApplicationRecord

  # Associations
  belongs_to :user

  def style?
    self.kind == "Stylesheet"
  end

end

app/models/provider.rb
class Provider < ApplicationRecord

  # Associations
  belongs_to :user
  has_many :updates

  def authorized?
    !self.token.blank?
  end

  def key
    self.class.to_s.downcase
  end

end

app/models/twitter.rb
class Twitter < Provider

  def sync
    if self.token && self.secret
      oauth_consumer = OAuth::Consumer.new(self.api_key, self.api_secret, { site: "https://api.twitter.com", scheme: :header })
      access_token = OAuth::AccessToken.from_hash(oauth_consumer, { oauth_token: self.token, oauth_token_secret: self.secret})
      response = access_token.get("https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=#{self.username}")
      feed = JSON.parse(response.body)
      feed.each do |upd|
        if Update.where(originalid: upd['id_str'], provider_id: self.id).count == 0
          status = self.updates.build({
            originalid: upd['id_str'],
            heading: upd['text'].gsub(/https:\/\/.*/, ""),
            link: upd['text'].scan(/https:\/\/.*/),
            posted_on: upd['created_at']
          })
          status.save
        end
      end
    end
  end

end

app/models/update.rb
class Update < ApplicationRecord

  # Associations
  belongs_to :provider

  # Validations
  validates :originalid, uniqueness: { scope: :provider_id, message: "should appear only once per provider to avoid duplicates" }

end

app/models/user.rb
class User < ApplicationRecord

  # Associations
  has_many :pages, -> { order('position') }
  has_many :providers, -> { order('type') }
  belongs_to :stylesheet, foreign_key: 'page_id', class_name: 'Page', optional: true

  # Include devise modules
  devise :database_authenticatable, :registerable, :confirmable, :validatable, :confirmable, :lockable, :rememberable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  include Pagy::Backend

  layout 'site'

  before_action :load_site

  # GET /
  def home
    @pagy, @records = pagy(Update.all)
  end

  # GET /projects
  def show
    @page = Page.where(name: params[:slug]).first
    if @page.style?
      render plain: @page.body, layout: false, content_type: "text/css"
    else
      render 'show'
    end
  end

  private

    def load_site
      @site = User.first
      @pages = @site.pages.where(kind: 'Static Page')
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autosite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'page_editor', 'data-turbolinks-track': 'reload' if controller.controller_name == 'pages' %>
    <%= javascript_pack_tag 'provider_editor', 'data-turbolinks-track': 'reload' if controller.controller_name == 'providers' %>
  </head>
  <body>
    <%= image_tag "logo.png", id: "logo" %>
    <nav>
      <%= link_to t('views.site.name'), manage_site_url %>
      <%= link_to t('views.pages.name'), manage_pages_url %>
      <%= link_to t('views.providers.name'), manage_providers_url %>
      <% if user_signed_in? %>
        <%= link_to t('views.layout.sign_out'), destroy_user_session_url, method: :delete %>
      <% else %>
        <%= link_to t('views.layout.sign_in'), new_user_session_url %>
      <% end %>
    </nav>
    <section id="notices">
      <% if notice %><p class="notice"><%= notice %></p><% end %>
      <% if alert %><p class="alert"><%= alert %></p><% end %>
    </section>
    <section id="main">
      <%= yield %>
    </section>
    <footer>
      <a href="https://github.com/paceline/autosite">Autosite</a> <%= t('views.layout.footer') %>
    </footer>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @site.site_title %></title>
    <link href="/<%= @site.stylesheet.name %>" media="all" rel="stylesheet" type="text/css" />
    <%= @site.site_tracker_code.html_safe %>
  </head>
  <body>
    <div id="content">
      <div id="header">
        <ul>
          <li><a href="/">Home</a></li>
          <% @pages.each do |page| %>
            <li><a href="/<%= page.name %>"><%= page.title %></a></li>
          <% end %>
        </ul>
        <%= yield %>
    </div>
    <%= @site.site_footer.html_safe %>
  </body>
</html>

app/views/site/home.html.erb
  <%= image_tag "home.png" %>
</div>
<div id="feed">
  <% @records.each_with_index do |u,i| %>
    <div id="update_<%= i %>">
      <h1>
		    <a href="<%= u.link %>" class="user_link"><%= u.provider.username %></a>
		    <a href="<%= u.link %>"><%= u.heading %></a>
      </h1>
      <% if u.content %><p><a href="<%= u.link %>"><%= u.content.truncate(150) %></a></p><% end %>
      <p class="link">
        <%= time_ago_in_words(u.posted_on) %> ago on <a href="http://<%= u.provider.class.to_s %>.com"><%= u.provider.class.to_s.capitalize %></a>
      </p>
    </div>
  <% end %>
</div>
<%== pagy_nav(@pagy) %>

app/views/site/show.html.erb
  <%= image_tag "#{@page.name}.png" %>
</div>
<%= @page.body.html_safe %>